spring:
  application:
    name: eureka-cluster

---
server:
  port: 7777

spring:
  application:
    name: eureka-cluster # 集群取一致的服务名称
  profiles: dev
  cloud:
    inetutils:
      ignored-interfaces:
        -VMware Network Adapter VMnet1
        -VMware Network Adapter VMnet8
      ##preferredNetworks: 192.168.79

eureka:
  instance:
    hostname: eureka7777.com #eureka服务端的实例名称 需要与EUREKA服务器的IP地址保持一致或DNS一致
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7778.com:7778/eureka/,http://eureka7779.com:7779/eureka/

---

server:
  port: 7778

spring:
  application:
    name: eureka-cluster # 集群取一致的服务名称
  profiles: test
  cloud:
    inetutils:
      ignored-interfaces:
        -VMware Network Adapter VMnet1
        -VMware Network Adapter VMnet8
      ##preferredNetworks: 192.168.79

eureka:
  instance:
    hostname: eureka7777.com #eureka服务端的实例名称 需要与EUREKA服务器的IP地址保持一致或DNS一致
  client:
    register-with-eureka: true     #false表示不向注册中心注册自己。
    fetch-registry: true     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7777.com:7777/eureka/,http://eureka7779.com:7779/eureka/
